// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9Oh3oCpeDd9_WEu-2aJqKIvUbCVdiLmM',
    appId: '1:720809979249:web:64cc44624ea2faeaf49ad0',
    messagingSenderId: '720809979249',
    projectId: 'graduationproject-33e4c',
    authDomain: 'graduationproject-33e4c.firebaseapp.com',
    storageBucket: 'graduationproject-33e4c.appspot.com',
    measurementId: 'G-HYLDJE2MGY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaECG5syO8itjbXP5FpQQ66ygkLgKf0DQ',
    appId: '1:720809979249:android:73ff7889748f2353f49ad0',
    messagingSenderId: '720809979249',
    projectId: 'graduationproject-33e4c',
    storageBucket: 'graduationproject-33e4c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD79Lo7pNOetvTHOfW8LhGng8hQAiKppMc',
    appId: '1:720809979249:ios:693bc6d28a6f3da4f49ad0',
    messagingSenderId: '720809979249',
    projectId: 'graduationproject-33e4c',
    storageBucket: 'graduationproject-33e4c.appspot.com',
    iosBundleId: 'com.example.graduationProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD79Lo7pNOetvTHOfW8LhGng8hQAiKppMc',
    appId: '1:720809979249:ios:2c5f2f2b16dff747f49ad0',
    messagingSenderId: '720809979249',
    projectId: 'graduationproject-33e4c',
    storageBucket: 'graduationproject-33e4c.appspot.com',
    iosBundleId: 'com.example.graduationProject.RunnerTests',
  );
}
